### ISSUE TITLE
failing to install via pip

### ISSUE THREAD

**Issue by dilkash-manghani** [edouardswiac/python-edgar#4] opened 2018-07-29 10:16 UTC
If i try to install library via pip , in setup.py it it not able to find README.md

**Comment by edouardswiac** [comment] 2018-08-03 18:33
Thanks for reporting the issue! I'll fix it.

**Comment by edouardswiac** [comment] 2018-08-07 05:50
I think the issue is fixed with 2.5. Can you try again?

**Closed as completed** 2018-08-12 01:00 UTC
